- pom.xml
Prevents NoSuchMethodErrors when running the application
> Added servlet exclusion for cobertura dependency

- .travis.yml
- docker-compose.yml
- pom.xml
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
An example of how we could localise our integration testing to:
* Increase code change feedback
* Speed up end to end/acceptance test builds
* Self document how services behave
Create integration tests to test an upload of a bres sample file is
successful. The integration test requires the following services to be
running:
* postgres
* redis
* rabbitmq
* sftp
* ras-party
The tests could be extended to ensure messages are put on rabbitmq or
data has been inserted into the database. Ideally you would test these
via an API even if that means introducing them to make testing easier.
> Integration test for bres upload

- pom.xml
Surefire only runs test with the formats: "**/Test*.java",
"**/*Test.java", "**/*Tests.java", "**/*TestCase.java" so it isn't
necessary to exclude the IT. It was causing some issue with
maven-checkstyle-plugin. We were getting the error
```
[ERROR] Failed to
execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check
(test) on project samplesvc: Unable to parse configuration of mojo
org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check: Basic
element 'excludes' must not contain child elements```
> Remove IT excludes in surefire

- Dockerfile
- pom.xml
These changes are driven to allow us to release artifacts in a much simpler way. Currently we have a bunch of shell scripts that we maintain to do releases when this is a core part of maven to be able to bump version, create tags and deploy artifacts.
* Bump versions and remove snapshot 
Release 13 was done on a branch where the version was incremented. The version change hasn't made it's way back into master yet so this change skips that version. We are also removing the snapshot versions.
* Using optional dockerfile buildArgs
We have been fighting with the `COPY target/samplesvc*.jar` syntax when
there is  more that one samplesvc*.jar file that  exists in the target
directory. Thought it was fixed by the docker info change but the same
issue occurs when doing a release because it builds …
> 14 create release artifacts

- src/main/resources/database/changes/release-10.49.0/changelog.yml
- src/main/resources/database/changes/release-10.49.0/sample_add_uuids.sql
Fixed gen_random_uuid() bug on sample service startup by modifying one of the early liquibase scripts to force the creation of the pgcrypto extension.  Also needed to add validCheckSum entries for new and old versions of script so won't break when deployed to production.
> Fix gen random UUID bug

- pom.xml
- src/main/java/uk/gov/ons/ctp/response/sample/SampleBeanMapper.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/model/SampleAttributes.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/model/SampleUnit.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/repository/SampleAttributesRepository.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/ingest/CsvIngesterBusiness.java
- src/main/java/uk/gov/ons/ctp/response/sample/ingest/CsvIngesterCensus.java
- src/main/java/uk/gov/ons/ctp/response/sample/ingest/CsvIngesterSocial.java
- src/main/java/uk/gov/ons/ctp/response/sample/mapper/SampleUnitMapper.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributor.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/impl/SampleServiceImpl.java
- src/main/resources/application-test.yml
- src/main/resources/database/changelog-master.yml
- src/main/resources/database/changes/release-10.49.1/add_sample_attributes_table.sql
- src/main/resources/database/changes/release-10.49.1/changelog.yml
- src/test/java/uk/gov/ons/ctp/response/sample/TestFiles.java
- src/test/java/uk/gov/ons/ctp/response/sample/Unirest.java
- src/test/java/uk/gov/ons/ctp/response/sample/UnirestInitialiser.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/CsvIngesterBusinessTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/CsvIngesterCensusTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/CsvIngesterSocialTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/sample/mapper/SampleUnitMapperTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributorTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SendToCollExQueueTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/impl/SampleServiceImplTest.java
- src/test/resources/csv/social-survey-sample-missing-columns.csv
- src/test/resources/csv/social-survey-sample.csv
Social files currently have four required attribute fields and can contain an arbitrary number of non mandatory attributes. The attributes are described by a header row in the sample file.
Adds functionality to parse a social sample file, persist sample attributes and post attributes to collection exercise. When a file is uploaded it is parsed and validated. If valid, it will be saved to a sample attributes table in the sample database linked by the sample unit id (UUID). When a request is made for samples the sample unit and sample attributes and put on the sample delivery queue.
We have added integration tests to exercise the upload functionality and ensure they are published to the queue with the sample attributes. 
**How to test:**
Requires changes in these branches: …
> Load a social sample file

- src/main/resources/application-cloud.yml
- src/main/resources/application.yml
The spring-boot applications limit the size of http multipart file upload and requests based the value of `spring.http.multipart.max-file-size` & `spring.http.multipart.max-request-size`. We need to increase these limits on sample service to allow uploading full MBS sample (i.e. approx. 36,000 sample units) from one file.  
- Increasing the http multipart `max-file-size` limit to 10MB 
- Increasing the http multipart `max-request-size` limit to 12MB
Upload a sample file with 36,000 sample unit against any collection exercise. Check the sample upload is successful.
> Upload Full MBS Sample (approx. 36K units)

- .travis.yml
Travis will run `mvn install -DskipTests=true -Dmaven.javadoc.skip=true
-B -V` on the install step by default which runs the integration tests
and builds the docker containers which makes the build take twice as
long. Changing it to skip docker and integration tests
* Skip docker and IT on install
* Run integration tests in travis
Travis is green
Check integration tests aren't ran in `install` step on travis
> Run integration tests on travis

- docker-compose.yml
The SFTP being in the compose file wrongly indicates that the
rm-collection-exercise-service needs an SFTP server to run. There is no
dependencies on an SFTP server so removing.
Remove SFTP container from compose file
Integration tests pass in travis (See https://github.com/ONSdigital/rm-sample-service/pull/54)
> Remove SFTP container from compose

- docker-compose.yml
- pom.xml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
The Maven dependencies were not organised very logically. There were a couple of dependencies which could be removed. Also, the artifactory repos were missing, which meant that developers had to update their local settings.xml to be able to build the project.
1. Added section with "artifactory" profile, after the section
2. Added "spring-boot-starter-web" as first dependency, with tomcat exclusion
3. Removed "spring-boot-starter-jdbc" dependency
4. Removed "javax.servlet-api" dependency
5. Removed "spring-boot-starter-data-solr" dependency
6. Grouped all the spring dependencies together with a comment at the top and the bottom
7. Grouped the ONS dependencies together with a comment at the top and the bottom
8. Grouped the 3rd party dependencies together with a comment at the top and the …
> Tidied up Maven pom.xml

- src/main/resources/springintegration/party-creation-in.xml
Retries currently stop working after finite attempts irrespective of message because the existing key to identify messages 'headers.id' evaluates to just id, which means all messages coming through the service have this id. As a result, if there is a failure, the retry counter will record it against 'id' then will continue retrying until max interval is reached. To make messages unique, we change the spring expression to identify them as such, thus allowing retries to correctly function against a valid key.
SpEL now uses a degree of uniqueness to distinguish one failed message from another.
WIP
> Handle retries correctly

- pom.xml
correcting the service version back to 10.49.15-SNAPSHOT as this was changed by mistake in this PR: https://github.com/ONSdigital/rm-sample-service/pull/62, this is currently stopping the mvn release tool from tagging the next release
Version in the pom has been corrected to be 10.49.15-SNAPSHOT
> Correct the app version in the pom to 10.49.15-SNAPSHOT

- pom.xml
- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
Bug discovered by @ajmaddaford in CI-latest where JSON not being used for key-value pairs.
Instead of flipping logging to use JSON in a `CommandLineRunner.run()` method, we're using a `@Postconstruct` instead, which should always fire.
Run with `--spring.profiles.active=cloud` or hack the `application.yml` to set `CLOUD` logger and `useJson=true`
Related Trello card: https://trello.com/c/KNOUa0pq/349-update-logging-in-all-java-services-to-use-key-value-pairs
> Init JSON logging in PostConstruct method

- API.md
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/sample/config/DataGrid.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributor.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/resources/application-cloud.yml
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributorTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
Presently the Collection Exercise service doesn't know how many sample units it expects to be sent by the Sample service until it requests the sample units to be sent, which causes a race condition - if the sample units start arriving before Collex has managed to store the expected number to the database.
This was causing intermittent failures in the CI pipeline and in production, and a temporary fix was to ignore the count check if we didn't have an expected value, but this fix was less than ideal, because the race condition still potentially existed for very small sample sizes.
This fix is intended to close all the loopholes by asking for the number of expected sample units _before_ they start to be sent by the Sample service. This is **one of three** related PRs.
Added a new REST API …
> Add endpoint to get count of sample units

- pom.xml
We are seeing strange dates being returned by the Java Spring Boot REST APIs when there is a concurrency of 3 or 4 users hammering the endpoints. The dates are sometimes completely bogus (e.g. 30 February or 31 April). This is bad.
Updated rm-common-service so it they no longer uses `static` instances of a DateFormat object shared across threads which is *not thread safe*. The new version of rm-common-service is `10.49.18`.
Bug can be reproduced by hammering collex events endpoint (e.g. `http://[host]:[port]/collectionexercises/[collex id]>/events`) and checking to make sure that a date such as the `exercise_end` date is *always* being returned as the expected correct value. This bug only occurs when there are *multiple concurrent users*.
Trello: …
> New version of rm-common-service to fix DateFormat multithreading bug

- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
We're using more vanilla ISO8601 dates now, since a major bug was discovered where the dates were being mangled by a non-threadsafe date formatter. Not sure why we can't support the old date formats, but it's not really important.
Updated a test.
This is a part of a whole load of PRs attempting to fix a multithreading issue, causing mangled dates to be returned when the REST API is concurrently called by 3 or 4 users, which is bad.
Trello: https://trello.com/c/bGt4TX2Q/405-bug-bad-dates-being-returned-by-java-services-under-load
> Fix timezone specified in weird way

- src/main/resources/application-cloud.yml
- src/main/resources/application.yml
This is an out of date module/dependency and it is recommended to use the alternative one in the PR instead.
This mainly provides support for 'if exists' in SQL for database for when we do database transactions/migrations etc.
Updated to use correct dependency
- `mvn clean install` and check if all builds successfully
Card: https://trello.com/c/QwluwHSN/509-upgrade-postgresql-hibernate-dialect-from-deprecated-to-v9-for-all-java-services-s
> Added undeprecated database platform instead of current one in place 

- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
- src/main/java/uk/gov/ons/ctp/response/sample/ingest/CsvIngesterBusiness.java
- src/main/java/uk/gov/ons/ctp/response/sample/ingest/CsvIngesterCensus.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/CsvIngesterBusinessTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/CsvIngesterCensusTest.java
The Sample service is capable of processing up to 5 samples simultaneously - using multithreading - but the Liquibase CSV parser is not thread-safe. This causes occasional failures of our parallel acceptance tests. Also this is a **production** bug, which would cause issues if two large-ish samples were uploaded at roughly the same time.
Use of the `@Cachable` annotation was being ignored by Spring, because AOP cannot work when one function calls another within the same class.
Thread-safety has been achieved using a `synchronised` block around the piece of code that isn't thread-safe.
This has been extensively tested during the performance enhancement work. To test it, upload two large samples into two different collection exercises at roughly the same time. They should process without an …
> Fix multithreading bug with CSV parsing

- API.md
I was checking the endpoints for this service and noticed that /sampleunits did not have documentation. When I tried to access the endpoint, however, I realised that it is necessary to pass in a postcode, which the Postgres database doesn't keep. As such, I don't think it is possible to use this endpoint. I have checked a few of the other services and this endpoint does not appear to be used, so I left a note to mark the endpoint as potentially redundant.
Updated API.md file.
[Trello card](https://trello.com/c/xZYE0DQO)
> documented redundant /sampleunits endpoint

- _infra/helm/sample/templates/deployment.yaml
- _infra/helm/sample/values.yaml
The helm charts needed to have the option of selecting different repos when a developer is testing changes.
- The `deployment.yaml` now switches to the devRepo if the `latest` tag is not set.
- Added the devRepo to `values.yaml`. As of now, it is the same as the current image's repo, but will be different in prod and pre-prod.
[Trello card](https://trello.com/c/fLbRN0qG)
> added devRepo

- pom.xml
- src/main/java/libs/common/error/RestExceptionHandler.java
- src/main/java/libs/common/retry/CTPUnknownHostRetryPolicy.java
- src/main/java/libs/common/state/BasicStateTransitionManager.java
- src/main/java/libs/common/time/DateTimeUtil.java
- src/main/java/libs/common/util/AggregatedDateFormat.java
- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/ingest/CsvIngesterBusiness.java
- src/main/java/uk/gov/ons/ctp/response/sample/ingest/CsvIngesterCensus.java
- src/main/java/uk/gov/ons/ctp/response/sample/ingest/CsvIngesterSocial.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/EventPublisher.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/PartyPublisher.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/PartyReceiver.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/SampleOutboundPublisher.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/SampleUnitPublisher.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributor.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitSender.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/CollectionExerciseJobService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/PartySvcClientService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleReportService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/resources/logback.xml
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
Godaddy logging is abandonware. use slf4j with logback backend.
where godaddy uses `log.with("key", value).info("message")`, logback uses `log.info("message", kv.("key", value))`
Very similar and allows for outputting objects in JSON format.
> Remove godaddy

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
Replacing `set-env` command in GH Actions, disabled this week for security reasons.
- https://trello.com/c/5Pj2VUx5
> replace deprecated cmd in GitHub Actions

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
- _infra/helm/sample/values.yaml
Add request/limit to the proxy container.
This is required for a HPA to detect the current request for a pod as a sum of all containers.
> add proxy request/limits

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/domain/repository/SampleUnitRepository.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
Stops a sample unit being created twice within a sample summary
> Stop duplicate samples being created within a single sample summary

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/domain/repository/SampleUnitRepository.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
Changing to exist because it is possible under heavy load for the sample unit to be created twice and then the query to get one fails.
This should hopefully stop the majority of duplicates being created in the system.
> Use exist rather than getting the sample unit

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/domain/repository/SampleSummaryRepository.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/repository/SampleUnitRepository.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributor.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitSender.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributorTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitSenderTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
JPA in Spring Boot 2.4 requires findById to return Optional
Run acceptance tests
https://trello.com/c/GsbrJG9u/572-s31a-spring-boot-2-upgrade-sample-service
> JPA fixes - use Optional for findById and correct call to activate sample summary

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
Including the update state calls within the same database transaction to stop the sceranio where a sample unit can be stuck in INIT state and therefore not distributed to collection exercise.
Run acceptance tests
NA
> Include the update state calls within the same database transaction

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
- src/test/resources/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.SampleSummary.json
The original sample summary check method use to check the number of sample units for a given sample summary in PERSISTED state against the total number of sample units created for that sample summary in any state. This worked before as a sample unit was only moved to PERSISTED state once a request had been sent to party. As the rabbit queue for sending requests to party acted like a throttle it meant all sample units were created before the requests to party was completed and this check worked.
However this no longer works as csv-worker is creating the party objects at the same time as the sample units, so we end up trying to activate the sample summary multiple times resulting in transition errors.
What the check actually should be, and probably should have been from the beginning is to …
> Fix activate sample summary check

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
Temporarily need this info back to fix a spinnaker issue deploying an old version with the most recent chart
> Aadd Party information back into the deployment yaml to fix production

- .github/workflows/main.yml
- src/main/java/uk/gov/ons/ctp/response/client/PartySvcClient.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryEnrichmentService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/sample/client/PartySvcClientTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryEnrichmentServiceTest.java
The /parties/type/{type}/ref/{ref} endpoint in party is being removed in favour of /businesses/ref/{ref}. This PR changes over to it. Functionally there should be no change as those 2 endpoints have been mapped to the same function in party for months now.
> Change party url to business url

- src/main/java/uk/gov/ons/ctp/response/client/CollectionInstrumentSvcClient.java
- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
Removing cacheable from the collection instrument service client as it causes the acceptance tests to fail if you re-run them
Run acceptance test more than once
https://trello.com/c/lsGFcRzR/440-s39-ce-sample-distribution-phase
> Remove cacheable collection instrument

- _infra/helm/sample/Chart.yaml
- diagrams/sample-unit-state.puml
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryDistributionService.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryDistributionServiceTest.java
When changing to sample v2, I forgot to change the state of the sample unit once it was sent.  Before this PR it would stay at PERSISTED, now it changes form PERSISTED to DELIVERED once it's been sent to case.
Note:  DELIVERED used to mean 'sent to collection exercise', where it would be sent from collection exercise to case.  Now DELIVERED means 'sent to case'
> Add sample unit state change on delivery to case

- _infra/helm/sample/Chart.yaml
- diagrams/sample-summary-state.puml
- diagrams/sample-unit-state.puml
- openapi.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/SampleSummaryActivation.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryActivationException.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryActivationService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryEnrichmentService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/state/SampleSvcStateTransitionManagerFactory.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryEnrichmentServiceTest.java
If a sample file fails to activate then the sample summary should be moved to a failed state and the samples that have caused the failure should also be marked as failed.
The endpoint to request sample units for sample summary has also been modified to allow a parameter to be passed to retrieve samples of a specific state. This will allow collection exercise to retrieve the failed samples and determine why they are an issue, the result of which will eventually be displayed to a user.
1. Deploy to your env
1. load a sample file which will failed (i.e. an invalid form type)
https://trello.com/c/Q5mkQDUb/900-bug-return-sample-unit-validation-errors-to-ce
> Sample Unit validation

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
This spams our logs and adds nothing
https://trello.com/c/JirTzMVG/1242-clean-up-excessive-logging-of-collection-instrument-cache-evicted
> Remove excessive logging about cache evictions

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
This PR updates Github actions to fix "service_account_key" has been deprecate. Replacing it with google-github-actions/auth in both main.yml and comment.yml
For main.yml check https://github.com/ONSdigital/rm-sample-service/runs/7211174971?check_suite_focus=true
For comment.yml see https://github.com/ONSdigital/response-operations-ui/pull/747 on how I tested in response-operations, as it is a virtual copy bar the service I didn't repeat it here
> Fix security account key deprecation

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
During a sample load, the app can be unresponsive to healthchecks even though nothing is wrong.  This change just gives the app a little more time to reply and checks slightly less frequently so that k8s is less likely to kill a pod that's just busy rather then unhealthy.
> Edit timeouts in helm chart

- README.md
- _infra/helm/sample/Chart.yaml
- diagrams/ingest-sequence.puml
- openapi.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/SampleSummaryLoadingStatus.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
Prior to this PR, loading a sample meant the sample service would hit the database once to load the sample unit, then again to get the count of all the sample units to see if it was done yet.  If it wasn't then it'd not do anything else, if all the sample units had been loaded then it would transition the state of the sample summary to ACTIVE (which let the things that cared know that the sample load was complete).
This new PR changes that.  During the sample load it does the 1 call per unit that the current one does to save it to the database, but now there is a separate http endpoint that needs to be called to check if all the sample units for a sample summary have been loaded, and then change the status. 
Doing it this way results in much much less strain on the database as getting the …
> Add endpoint for sample summary status change

- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
Currently on a push to a PR each repo builds to latest in onsrasrm-management, however this is the default artifact for all builds when using spinnaker. This means if any change to the charts are made and a PR is created it can and will break dev for everyone. 
Check the build (Publish dev Chart) and make sure it is writing naming the artifact correctly, it should be xx-pr-xx.tgz. You can also check on GCP in ons-rasrmbs-management that the artifact was written out at the right time
> update publish dev chart

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
This PR adds a wait time for cloud_sql_proxy and stops verbose logging. Currently we deploy the app with a side car cloud_sql_proxy container to access the db. However when a pod is redeployed and the proxy container is sent a SIGTERM the container does not close down gracefully and will kill all connections instantly (i.e sql queries). This naturally gets passed back up the chain to the respondent who will get an error. With us currently using a default pool of 5 and overflow of 10, it means anything up to 15 respondents could get an error when we deploy a new release to prod, which ain't good.
It almost certainly is the reason we see hanging queries and spikes on rollouts in Grafana. This PR adds a term_timeout which will allow the proxy to complete it's query (at least give it 30 …
> RAS-850 Cloud sql proxy term timeout and verbose

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
- docker-compose.yml
- src/main/java/uk/gov/ons/ctp/response/client/CollectionExerciseSvcClient.java
- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
- src/main/java/uk/gov/ons/ctp/response/sample/config/AppConfig.java
- src/main/java/uk/gov/ons/ctp/response/sample/config/CollectionExerciseSvc.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/SampleReadinessRequestDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/sample/client/CollectionExerciseSvcClientTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
This PR adds the configuration and request needed to let collection exercise know when the sample is ready and loaded so that when a sample is loaded in response operations, and all other values are loaded, the `Set Ready for live` button appears.
- Deploy this PR to your environment
- Must be deployed using helm because there are changes to the deployment which are not reflected when deploying through spinnaker
- Update the values.yaml file for your environment (including the gcp values)
- Must be deployed last
- Deploy https://github.com/ONSdigital/rm-collection-exercise-service/pull/319 to your environment
- Deploy https://github.com/ONSdigital/response-operations-ui/pull/888 to your environment
- Set up a collection exercise in this order
- Required event dates
- A collection …
> RAS-638 Investigate how "Ready for live" button works, when replacing sample file (track time)

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
This PR replaces set-output within the .github workflow file with environment variables to fix a deprecation with set-output. It also updates actions/auth to v2.
Check the github builds for any deprecation warnings and ensure the workflow works after the changes.
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-915
> Update set-output to environment variables

- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/CollectionExerciseEndActivation.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/SampleSummaryActivation.java
This PR migrates the spring cloud pubsub dependencies to google cloud. The functionality should remain the same after the migration. 
Run local and integration tests. 
N.B. the local test will show two failing integration tests, there is a card to address this in the backlog. 
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-1080
> Migrate Spring cloud pubsub to google cloud pubsub

- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
- docker-compose-down.sh
- docker-compose-up.sh
- docker-compose.yml
- pom.xml
This PR replaces our use of the `docker-compose-maven-plugin` as that is still using `docker-compose` that has been removed
Recreated from https://github.com/ONSdigital/rm-sample-service/pull/255 with GPG signing
Check the build
[RAS-1238](https://jira.ons.gov.uk/browse/RAS-1238)
> RAS-1238 Update to docker compose from docker-compose

- _infra/helm/sample/Chart.yaml
- pom.xml
Spring Boot 2.6 is out of support. This upgrades from 2.6 to 2.7
This also upgrades a number of other dependencies including google cloud libraries. Initially the application built and tests passed. However, when deployed into GCP it failed to start due to Spring Boot / GCP library dependencies. I've had to find the most recent compatible GCP library (4.8.0).
Ensure it builds, deploys and the acceptance tests pass. Ensure the app doesn't restart when deployed into a GCP environment due to PubSub bean dependencies.
> Upgrading Spring Boot to 2.7

- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
Upgrades actions/cache from deprecated version to v4
Check the github actions build for successful use of v4
https://jira.ons.gov.uk/browse/RAS-1409
> Upgrade actions/cache to v4

- _infra/helm/sample/Chart.yaml
- docker-compose.yml
PubSub emulator has been migrated from GCR to GAR
Check the tests run in GHA and locally
https://jira.ons.gov.uk/browse/RAS-1423
> Use migrated GAR pubsub-emulator image
