- pom.xml
- src/main/java/uk/gov/ons/ctp/response/sample/domain/model/SampleSummary.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/impl/SampleServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/impl/SampleServiceImplTest.java
- src/test/resources/uk/gov/ons/ctp/response/sample/service/impl/SampleServiceImplTest.PartyDTO.json
Pass Sample Summary ID to Party service.
> Post Sample Summary ID to Party service.

- README.md
Add documentation to allow skipping of IT and docker services locally
> Add skipITs and docker.skip docs

- src/main/resources/application.yml
Align default port numbers for all apps. Port numbers for all apps can be found here: https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/94863418/Developer+Environment+Port+Mappings
> aligning ports

- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/impl/SampleServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/impl/SampleServiceImplTest.java
* Change sample type from bres to B
* Add default scenario for unimplemented types that will raise a
unsupported exception
* Backfill some upload sample tests
https://trello.com/c/CDq3n7Q2/25-us009-load-sample-in-context-of-a-ce
> Change sample type to B

- .travis.settings.xml
- Jenkinsfile
- manifest-template.yml
- pom.xml
- src/main/resources/application-cloud.yml
A pipeline to
1. Build and unit test the source code
1. Deploy the snapshot artifact
1. Deploy to dev CF
1. Deploy to CI CF based on user feedback
1. Create release artifact based on user feedback
1. Deploy to TEST based on user feedback
Jenkins home with blueocean skin (showing list of 
Build history for pipeline
Running the pipeline
> Create pipeline for build and release

- src/main/resources/database/changes/release-10.49.0/changelog.yml
- src/main/resources/database/changes/release-10.49.0/sample_add_uuids.sql
as they don't seem to work in all cases (Dockerfile changes are already merged into master - just reverting the generate_random_uuid change)
> Reverted changes to fix generate_random_uuid

- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/impl/SampleServiceImpl.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/impl/SampleServiceImplTest.java
Refactored sample service to move async out of SampleServiceImpl and into SampleEndpoint as per earlier PR comment
> P2 load sample additional

- scripts/load_social_sample_file.sh
We can't upload social sample files via the UI at the moment because the
type of social file is hard-coded in response-operations-ui. This script
allows a sample to be uploaded in a simple way without the UI.
A simple script to upload social sample files. It will validate the
arguments and then make a curl request to upload a file.
1. Checkout rm-sample-service -b upload-a-social-sample-file
1. Start docker-compose file `docker-compose up -d`
1. Change `application.yml` sections to the postgres user
```
liquibase:
user: postgres
password: postgres
spring:
datasource:
username: postgres
password: postgres
```
1. Start service by running `SampleSvcApplication` in intellij
1. Get a sample file `wget https://raw.githubusercontent.com/ONSdigital/rm-sample-service/load-a-social-sample-file/src/t …
> Script for uploading social sample file

- API.md
The doc doesn't match the code.
> Correct URI for fetching a sample summary by ID

- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
- src/test/resources/csv/social-survey-sample-no-space-postcode.csv
- src/test/resources/csv/social-survey-sample-partial-postcode.csv
- src/test/resources/csv/social-survey-sample-with-space-postcode.csv
This PR adds in IT for returning social case details depending on the postcode search. This was factored out from the acceptance tests https://github.com/ONSdigital/rasrm-acceptance-tests/pull/163
Added IT and csv data
Run IT `mvn` and check they pass
> Added IT tests for postcode search

- .travis.yml
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
Checking travis build fails with failing test
> Check travis fails

- pom.xml
We recently had to do a bug fix off an earlier release and create a jar from it in artifactory. Because of that we are out of step and the snapshot version needs updating
> Update snapshot version to 10.49.19

- src/main/java/uk/gov/ons/ctp/response/sample/ingest/CsvIngesterBusiness.java
Presently the sample file is CSV parsed & validated using a single thread, which means its performance will degrade linearly depending on the size of file.
When we load samples, there can be a long delay before the user is presented with any feedback saying that the file contents aren't valid.
The CSV parsing and validation is now done across 200 threads in-memory after the file has been loaded. This should be OK for samples of up to 110k without increasing the amount of memory required, because the memory requirements are not significantly increased.
Load a large sample - it should be much quicker.
Load a sample with duplicate RU refs - it should quickly report the problem.
Load a sample with a row which has an incorrect number of columns - it should quickly report the problem.
Trello: …
> Validate CSV using multithreading

- _infra/helm/sample/templates/deployment.yaml
- _infra/helm/sample/templates/service.yaml
- _infra/helm/sample/values.yaml
> standardise db config

- _infra/helm/sample/templates/deployment.yaml
- _infra/helm/sample/values.yaml
> add sql proxy

- _infra/helm/sample/templates/deployment.yaml
> Adding SFTP secret value

- _infra/helm/sample/templates/deployment.yaml
- _infra/helm/sample/values.yaml
> SFTP config

- _infra/docker/Dockerfile
> Remove user as it doesnt have permissions

- _infra/helm/sample/values.yaml
The service port needed to be changed to 8080.
Changed service port to 8080.
[Trello card](https://trello.com/c/iBBXBpLll)
> changed service port

- _infra/helm/sample/templates/deployment.yaml
- _infra/helm/sample/values.yaml
- pom.xml
- src/main/resources/application.yml
Zipkin needed to be removed from the various services.
Removed all mentions of Zipkin.
[Trello card](https://trello.com/c/YZ9aio6I)
> Removing zipkin

- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
> code that replaces concourse

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
> Make dev docker tag changes

- _infra/helm/sample/Chart.yaml
- src/main/java/libs/sample/validation/BusinessSampleUnit.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/BusinessSampleUnitDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/SampleUnitDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/UnknownSampleSummaryException.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
Adding an endpoint for adding an individual sample, this is to allow integration with the new csv uploader and csv workers.
New endpoint to post a sample and a new method on SampleService to save it to the database
Run the unit tests
> Add endpoint for adding a sample unit

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
Adding an endpoint to create a sample summary. This will be invoked by the new sample file uploader.
> Adding endpoint to create a sample summary

- _infra/helm/sample/templates/deployment.yaml
- _infra/helm/sample/values.yaml
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/BusinessSampleUnitDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitSender.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
> Sample summary update

- _infra/helm/sample/Chart.yaml
- _infra/spinnaker/deployment-full.json
> syncronize default helm chart

- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
- _infra/spinnaker/prodDeploy.json
Update needed to hash in production pipeline, to use template with release parameters.
Also updated GH Actions to ignore Spinnaker changes in build trigger.
- https://collaborate2.ons.gov.uk/jira/browse/RAS-141
> update SHA in prod template, exclude spinnaker from GH triggers

- .github/workflows/comment.yml
- _infra/helm/sample/Chart.yaml
> change from sandbox to dev

- .github/workflows/comment.yml
- _infra/helm/sample/Chart.yaml
> fix injection

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/hpa.yaml
- _infra/helm/sample/values.yaml
> add min replicas

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/values.yaml
> Remove duplicate values from helm chart

- .github/workflows/comment.yml
- _infra/helm/sample/Chart.yaml
Use new github action created specifically for ras-rm pr comments.
https://github.com/ONSdigital/ras-rm-spinnaker-action
> new comment action

- .github/workflows/main.yml
- Dockerfile
- _infra/docker/Dockerfile
- pom.xml
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
> Java 11 update

- README.md
- _infra/helm/sample/Chart.yaml
> Remove unused badges

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/main/resources/springintegration/party-creation-in.xml
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributorTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitMapperTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitSenderTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/StoreCollectionExerciseJobTest.java
Upgrades us from the 1.5.x branch (which has been end-of-lifed for 2 years) to 2.4.4
Run acceptance tests/unit tests, though I have also done this.
https://trello.com/c/GsbrJG9u/572-s31a-spring-boot-2-upgrade-sample-service
> Upgrade to Spring Boot 2.4.4

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
I missed something in deployment.yaml
It only breaks in staging, so this will need to be merged to test
https://trello.com/c/GsbrJG9u/572-s31a-spring-boot-2-upgrade-sample-service
> Fix for Spring Boot work

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
Reverts ONSdigital/rm-sample-service#157
> Revert "Fix for Spring Boot work"

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/main/resources/springintegration/party-creation-in.xml
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributorTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitMapperTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitSenderTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/StoreCollectionExerciseJobTest.java
Reverts ONSdigital/rm-sample-service#156
> Revert "Upgrade to Spring Boot 2.4.4"

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/main/resources/springintegration/party-creation-in.xml
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointUnitTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributorTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitMapperTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitSenderTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/StoreCollectionExerciseJobTest.java
Reverts ONSdigital/rm-sample-service#159
> Revert "Revert "Upgrade to Spring Boot 2.4.4""

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
Reverts ONSdigital/rm-sample-service#158
> Revert "Revert "Fix for Spring Boot work""

- _infra/helm/sample/Chart.yaml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
> Set liquibase schema for all environments and default schema for the unit tests

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
> Update sql-proxy from 1.16 to 1.22

- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
- docker-compose.yml
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/sample/config/ThreadPoolConfig.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/exception/AsyncSampleUncaughtExceptionHandler.java
- src/main/java/uk/gov/ons/ctp/response/sample/party/PartyUtil.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/CollectionExerciseJobCreationRequestDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleDistributionException.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributor.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitMapper.java
- src/main/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitSender.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/PartyService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/test/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpointIT.java
- src/test/java/uk/gov/ons/ctp/response/sample/scheduled/distribution/SampleUnitDistributorTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/PartyServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
Use GCR images for integration tests
https://trello.com/c/mGQ7YEeN/678-bug-use-gcr-images-for-integration-tests
> GCR images for integration tests

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/domain/model/CollectionExerciseJob.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/model/SampleSummary.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/model/SampleUnit.java
- src/main/resources/database/changelog-master.yml
- src/main/resources/database/changes/release-16/add_column_underscores.sql
- src/main/resources/database/changes/release-16/changelog.yml
As part of the ongoing database rationalisation work, renaming everything to use underscores to maintain consistency
https://trello.com/c/PuzXi1Ih/579-s37-rasrm-database-rationalisation-sample-service
> Database rationalisation

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
Reverts ONSdigital/rm-sample-service#182
> Revert "Aadd Party information back into the deployment yaml to fix production"

- _infra/helm/sample/Chart.yaml
> Bump version

- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
> Update chart versions automatically

- src/main/java/uk/gov/ons/ctp/response/client/SurveySvcClient.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/model/SampleSummary.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleSummaryEnrichementEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryEnrichmentService.java
- src/main/resources/database/changes/release-17/add_collection_exercise_to_sample_summary.sql
- src/main/resources/database/changes/release-17/add_survey_id_to_sample_summary.sql
- src/main/resources/database/changes/release-17/changelog.yml
- src/test/java/uk/gov/ons/ctp/response/sample/client/SurveySvcClientTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryEnrichmentServiceTest.java
Enrich sample summary with collection exercise id and survey id
> Enrich sample summary

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
- _infra/helm/sample/values.yaml
- src/main/java/uk/gov/ons/ctp/response/client/PartySvcClient.java
- src/main/java/uk/gov/ons/ctp/response/sample/config/GCP.java
- src/main/java/uk/gov/ons/ctp/response/sample/config/PartySvc.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/model/SampleSummary.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleSummaryDistributionEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/PubSub.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/SampleUnitPublisher.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/SampleLinkCreationRequestDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/SampleLinkDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/SampleUnitChildrenDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/SampleUnitDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/SampleUnitParentDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/NoSampleUnitsInSampleSummaryException.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryDistributionService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryEnrichmentService.java
- src/main/resources/application.yml
- src/main/resources/database/changes/release-17/add_mark_for_deletion_to_sample_summary.sql
- src/main/resources/database/changes/release-17/changelog.yml
- src/test/java/uk/gov/ons/ctp/response/sample/client/PartySvcClientTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryDistributionServiceTest.java
> V2 distribution

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
> Update environment variable

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
> Fix copy paste channel mistake

- _infra/helm/sample/Chart.yaml
- pom.xml
- src/main/java/uk/gov/ons/ctp/response/client/CollectionInstrumentSvcClient.java
- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
- src/test/java/uk/gov/ons/ctp/response/sample/config/CachingTestIT.java
This was added to collection exercise to improve performance of the sample validation and was missed during the sample v2 implementation.
> Adding the Collection Instrument cache from collection exercise

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/AsyncConfiguration.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/repository/SampleUnitRepository.java
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryActivationService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryDistributionService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryEnrichmentService.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleServiceTest.java
- src/test/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryDistributionServiceTest.java
We enrich samples one at a time, but this could be multithreaded.
https://trello.com/c/hQ3pazls/888-s42-use-parallelstreams-to-send-enrich-samples
> Use parallelstreams to send cases

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
Endpoint needs a transaction to interact with a stream
n/a
> Adding transaction to endpoint

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/endpoint/SampleEndpoint.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleService.java
> Move list conversion into sample service  

- _infra/helm/sample/Chart.yaml
- src/main/resources/database/changelog-master.yml
- src/main/resources/database/changes/release-19/add_index_to_sample_unit_table.sql
- src/main/resources/database/changes/release-19/changelog.yml
Adding index to the sample unit table to improve database efficiency when loading a sample
Load a large sample file 
https://trello.com/c/NyNQ5sou/955-bug-add-index-sample-count
> Adding index to the sample unit table

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/values.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/repository/SampleSummaryRepository.java
- src/main/java/uk/gov/ons/ctp/response/sample/domain/repository/SampleUnitRepository.java
- src/main/java/uk/gov/ons/ctp/response/sample/message/CollectionExerciseEndActivation.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/CollectionExerciseEndEventDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/representation/SampleSummaryDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/CollectionExerciseEndService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/SampleSummaryActivationService.java
- src/main/resources/application.yml
- src/test/java/uk/gov/ons/ctp/response/sample/service/CollectionExerciseEndServiceTest.java
consume collection exercise end events from collection exercise end topic and delete sample units and set sample summary status to complete
https://trello.com/c/88XQ97Ug/1042-sample-listen-for-exercise-end-event
> Sample listen for exercise end event

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
add missing value from helm deployment
https://trello.com/c/88XQ97Ug/1042-sample-listen-for-exercise-end-event
> add subription to deployment yaml

- _infra/helm/sample/Chart.yaml
- src/main/java/uk/gov/ons/ctp/response/sample/SampleSvcApplication.java
- src/main/java/uk/gov/ons/ctp/response/sample/config/GCP.java
correctly map variable for collection exercise end subscription
https://trello.com/c/88XQ97Ug/1042-sample-listen-for-exercise-end-event
> correct variable for collection exercise end

- _infra/helm/sample/Chart.yaml
- diagrams/sample-summary-state.puml
- src/main/java/uk/gov/ons/ctp/response/sample/representation/SampleSummaryDTO.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/CollectionExerciseEndService.java
- src/main/java/uk/gov/ons/ctp/response/sample/service/state/SampleSvcStateTransitionManagerFactory.java
- src/main/resources/database/changelog-master.yml
- src/main/resources/database/changes/release-21/changelog.yml
- src/main/resources/database/changes/release-21/create_state_complete_for_sample_summary_state.sql
Create state for completed in sample summary state in order for completed to be a valid state in database
https://trello.com/c/88XQ97Ug/1042-sample-listen-for-exercise-end-event
> create state for completed in sample summary state

- _infra/helm/sample/Chart.yaml
- _infra/helm/sample/templates/deployment.yaml
> Upgrade cloudsql proxy

- _infra/helm/sample/Chart.yaml
- pom.xml
After running maven in Sample service had some complains with the following libs being duplicated within the POM
spring-cloud-gcp-starter-pubsub
spring-integration-core
I have removed the duplicates and rebuilt and run tests.
Ensure applications functions as normal - no major changes were performed
https://trello.com/c/ZZSrZBku/2241-bug-duplicate-packages-within-pom-sample-service
> remove duplication package declaration

- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
Removal of deprecated github action
https://trello.com/c/JyPxSmDA/2298-replace-soon-to-be-deprecated-set-output-in-github-actions
> Fix setouput

- _infra/helm/sample/Chart.yaml
- pom.xml
- src/main/java/libs/common/error/CTPException.java
> Update the Maven fmt plugin

- _infra/helm/sample/Chart.yaml
- pom.xml
Testing out changing mockito inline to mockito core.
Deploy to environment, run acceptance tests, and test uploading sample file.
[Card](https://jira.ons.gov.uk/browse/RAS-803)
> change mockito inline to mockito core

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/sample/Chart.yaml
Pinning GHA versions to commit references
Check GHA
[RAS-1418](https://jira.ons.gov.uk/browse/RAS-1418)
**Not a production candidate**
> RAS-1418 EPIC: Unpinned tag for a non-immutable Action in workflow
